package tui

// adifContestIDs is the ADIF 3.1.7 Contest ID enumeration (III.B.5).
// Key is the Contest-ID value (as stored in ADIF). Value is the human-readable Description.
// Sourced from https://adif.org.uk/317/ADIF_317.htm#Contest_ID
var adifContestIDs = []struct {
	ID, Desc string
}{
	// ARRL / IARU / RSGB / DARC / REF / JARL major contests – keep at top for cycling.
	{"AP-SPRINT", "Asia-Pacific Sprint"},
	{"ARRL-10", "ARRL 10 Meter Contest"},
	{"ARRL-160", "ARRL 160 Meter Contest"},
	{"ARRL-222", "ARRL 222 MHz and Up Distance Contest"},
	{"ARRL-EME", "ARRL EME Contest"},
	{"ARRL-FIELD-DAY", "ARRL Field Day"},
	{"ARRL-RR-CW", "ARRL Rookie Roundup (CW)"},
	{"ARRL-RR-SSB", "ARRL Rookie Roundup (SSB)"},
	{"ARRL-RTTY", "ARRL RTTY Roundup"},
	{"ARRL-SCR", "ARRL School Club Roundup"},
	{"ARRL-SS-CW", "ARRL November Sweepstakes (CW)"},
	{"ARRL-SS-SSB", "ARRL November Sweepstakes (SSB)"},
	{"ARRL-UHF-AUG", "ARRL August UHF Contest"},
	{"ARRL-VHF-JAN", "ARRL January VHF Contest"},
	{"ARRL-VHF-JUN", "ARRL June VHF Contest"},
	{"ARRL-VHF-SEP", "ARRL September VHF Contest"},
	{"CQ-160-CW", "CQ WW 160m DX Contest (CW)"},
	{"CQ-160-SSB", "CQ WW 160m DX Contest (SSB)"},
	{"CQ-VHF", "CQ World Wide VHF Contest"},
	{"CQ-WPX-CW", "CQ WW WPX Contest (CW)"},
	{"CQ-WPX-RTTY", "CQ WW WPX Contest (RTTY)"},
	{"CQ-WPX-SSB", "CQ WW WPX Contest (SSB)"},
	{"CQ-WW-CW", "CQ WW DX Contest (CW)"},
	{"CQ-WW-RTTY", "CQ WW RTTY DX Contest"},
	{"CQ-WW-SSB", "CQ WW DX Contest (SSB)"},
	{"DARC-WAEDC-CW", "WAE DX Contest (CW)"},
	{"DARC-WAEDC-RTTY", "WAE DX Contest (RTTY)"},
	{"DARC-WAEDC-SSB", "WAE DX Contest (SSB)"},
	{"IARU-HF", "IARU HF World Championship"},
	{"IARU-R1-50-MHZ", "IARU Region 1 50 MHz Contest"},
	{"IARU-R1-145-MHZ", "IARU Region 1 145 MHz Contest"},
	{"IARU-R1-ATV", "IARU Region 1 ATV Contest"},
	{"IARU-R1-FIELD-DAY-CW", "IARU Region 1 Field Day (CW)"},
	{"IARU-R1-FIELD-DAY-SSB", "IARU Region 1 Field Day (SSB)"},
	{"IARU-R1-MICROWAVE", "IARU Region 1 Microwave Contest"},
	{"IARU-R1-UHF-MICROWAVE", "IARU Region 1 UHF/Microwave Contest"},
	{"IARU-R1-VHF", "IARU Region 1 VHF Contest"},
	{"JARL-ALL-CITY", "All JA City / Gun / AG Contest"},
	{"JARL-ACAG", "All Cities All Guns Contest (amended)"},
	{"NA-SPRINT-CW", "North America Sprint (CW)"},
	{"NA-SPRINT-RTTY", "North America Sprint (RTTY)"},
	{"NA-SPRINT-SSB", "North America Sprint (SSB)"},
	{"NRAU-BALTIC-CW", "NRAU Baltic Contest (CW)"},
	{"NRAU-BALTIC-SSB", "NRAU Baltic Contest (SSB)"},
	{"RAC-CANADA-DAY", "RAC Canada Day Contest"},
	{"RAC-CANADA-WINTER", "RAC Canada Winter Contest"},
	{"REF-160M", "REF 160m Contest"},
	{"REF-CW", "REF CW Contest"},
	{"REF-SSB", "REF SSB Contest"},
	{"REF-THFR", "REF THF Radio Contest"},
	{"RSGB-160M", "RSGB 1.8 MHz Contest"},
	{"RSGB-21-28-MHZ", "RSGB 21/28 MHz Contest"},
	{"RSGB-70CM", "RSGB 70 MHz Contest"},
	{"RSGB-80M-CC-CW", "RSGB 80m Club Championship (CW)"},
	{"RSGB-80M-CC-DATA", "RSGB 80m Club Championship (Data)"},
	{"RSGB-80M-CC-SSB", "RSGB 80m Club Championship (SSB)"},
	{"RSGB-AFS-CW", "RSGB AFS Contest (CW)"},
	{"RSGB-AFS-DATA", "RSGB AFS Contest (Data)"},
	{"RSGB-AFS-SSB", "RSGB AFS Contest (SSB)"},
	{"RSGB-CLUB-CALLS", "RSGB Club Calls Contest"},
	{"RSGB-COMMONWEALTH", "RSGB Commonwealth Contest"},
	{"RSGB-FT4", "RSGB FT4 Contest"},
	{"RSGB-IOTA", "RSGB IOTA Contest"},
	{"RSGB-LOW-POWER", "RSGB Low Power Field Day"},
	{"RSGB-NFD", "RSGB National Field Day"},
	{"RSGB-ROPOCO", "RSGB RoPoCo"},
	{"RSGB-SSB-FIELD-DAY", "RSGB SSB Field Day"},
	{"RSGB-VHF-NFD", "RSGB VHF NFD"},
	{"SAC-CW", "Scandinavian Activity Contest (CW)"},
	{"SAC-SSB", "Scandinavian Activity Contest (SSB)"},
	{"SPDXCONTEST-CW", "SP DX Contest (CW)"},
	{"SPDXCONTEST-RTTY", "SP DX Contest (RTTY)"},
	{"SPDXCONTEST-SSB", "SP DX Contest (SSB)"},
	{"STEW-PERRY", "Stew Perry Topband Challenge"},
	{"UKEICC-80M", "UKEICC 80m Contest"},
	{"UKEICC-DX-CW", "UKEICC DX Contest (CW)"},
	{"UKEICC-DX-SSB", "UKEICC DX Contest (SSB)"},

	// QRP / SKCC / NAQCC / FISTS etc.
	{"ARCI-FIELD-DAY", "ARCI Field Day"},
	{"FISTS", "FISTS CW Club Contest"},
	{"NAQCC-CW-SPRINT", "NAQCC CW Sprint"},
	{"NAQCC-CW-WEEKLY", "NAQCC CW Weekly Sprint"},
	{"NAQCC-EU-SPRINT", "NAQCC-EU Monthly Sprint"},
	{"QRP-ARCI", "QRP ARCI Contest"},
	{"QRP-ARCI-FIELD-DAY", "QRP ARCI Field Day"},
	{"RUN-FOR-THE-BACON", "Run for the Bacon QRP Contest"},
	{"SKCC", "SKCC Straight Key Century Club"},
	{"SKCC-WEEKDAY-SPRINT", "SKCC Weekday Sprint"},
	{"SKCC-WEEKEND-SPRINT", "SKCC Weekend Sprintathon"},

	// DIGI / RTTY / data modes
	{"BARTG-RTTY", "BARTG RTTY Sprint"},
	{"BARTG-SPRINT", "BARTG Sprint Contest"},
	{"BARTG-HF-RTTY", "BARTG HF RTTY Contest"},
	{"DMC-RTTY", "DMC RTTY Contest"},
	{"EA-RTTY", "EA RTTY Contest"},
	{"EPC-PSK63", "EPC PSK63 QSO Party"},
	{"EUCW-160M", "EUCW 160m Contest"},
	{"FCG-RTTY", "FCG RTTY Contest"},
	{"HELVETIA", "Helvetia Contest"},
	{"JARTS-WW-RTTY", "JARTS WW RTTY Contest"},
	{"NA-RTTY", "North American RTTY Sprint"},
	{"OK-OM-DX", "OK/OM DX Contest (SSB)"},
	{"OK-OM-DX-RTTY", "OK/OM DX Contest (RTTY)"},
	{"PACC-RTTY", "PACC RTTY Contest"},
	{"SARTG-HNY-RTTY", "SARTG New Year RTTY Contest"},
	{"SARTG-WW-RTTY", "SARTG WW RTTY Contest"},
	{"TARA-DIP-40", "TARA Dipole 40m Contest"},
	{"TARA-GRID-DIP", "TARA Grid Dip Contest"},
	{"TARA-PSK-RUMBLE", "TARA PSK Rumble Contest"},
	{"TARA-RTTY-MELEE", "TARA RTTY Melee"},
	{"TARA-SKIRMISH", "TARA Skirmish Contest"},
	{"UK-DX-RTTY", "UK DX RTTY Contest"},
	{"WAEDC-QTC", "WAE DX Contest QTC"},
	{"XMAS-RTTY", "XMAS RTTY Contest"},

	// VHF / UHF / microwave / EME / satellites
	{"AADX-EME", "AADX EME Contest"},
	{"AADX-VHF-UHF", "AADX VHF/UHF Contest"},
	{"EME", "EME Contest"},
	{"MICROWAVE-FD", "Microwave Field Day"},
	{"MOONBOUNCE", "Moonbounce Contest"},
	{"SAT-SPRINT", "Satellite Sprint"},
	{"UBA-6M-SPRING", "UBA 6m Spring Contest"},
	{"VHF-FM-MARATHON", "VHF FM Marathon"},
	{"VHF-REG-1-FIELD-DAY", "VHF Region 1 Field Day"},

	// International HF / DX
	{"ALL-ASIAN-CW", "All Asian DX Contest (CW)"},
	{"ALL-ASIAN-DX-SSB", "All Asian DX Contest (SSB)"},
	{"ARRL-DX-CW", "ARRL International DX Contest (CW)"},
	{"ARRL-DX-SSB", "ARRL International DX Contest (SSB)"},
	{"BALTIC-CONTEST", "Baltic Contest"},
	{"BENELUX-QSO-PARTY", "Benelux QSO Party"},
	{"CIS-DX", "CIS DX Contest"},
	{"CROATIAN-CW", "Croatian CW Contest"},
	{"CVA-DX-CW", "CVA DX Contest (CW)"},
	{"CVA-DX-SSB", "CVA DX Contest (SSB)"},
	{"DARC-10M", "DARC 10m Contest"},
	{"DARC-XMAS", "DARC XMAS Contest"},
	{"DIG-QSO-PARTY", "DIG QSO Party"},
	{"EA-CW", "EA CW Contest"},
	{"EA-DX-RTTY", "EA DX RTTY Contest"},
	{"EA-MAJESTAD-CW", "EA Majestad CW Contest"},
	{"EA-MAJESTAD-SSB", "EA Majestad SSB Contest"},
	{"EA-PSK63", "EA PSK63 Contest"},
	{"EA-SSB", "EA SSB Contest"},
	{"EA-VHF-ATLANTICO", "EA VHF Atlántico"},
	{"EBW", "European Bundeswehr Contest"},
	{"EU Sprint Contest", "EU Sprint Contest"},
	{"EU-HF-CHAMPIONSHIP", "EU HF Championship"},
	{"EU-WW-RTTY", "EU WW RTTY Contest"},
	{"F9AA-CUP", "F9AA Cup"},
	{"FOC-QSO-PARTY", "FOC QSO Party"},
	{"GAGARIN-CUP", "Gagarin Cup"},
	{"HA-DX", "HA DX Contest"},
	{"HELVETIA-CONTEST", "Helvetia Contest"},
	{"HOLYLAND", "Holyland Contest"},
	{"HSC-CW", "HSC CW Contest"},
	{"ICWC-MST", "ICWC Medium Speed Test"},
	{"INORC-CONTEST", "INORC Contest"},
	{"IOTA-CONTEST", "IOTA Contest"},
	{"IRTS-HF", "IRTS HF Contest"},
	{"JIDX-CW", "JIDX Contest (CW)"},
	{"JIDX-SSB", "JIDX Contest (SSB)"},
	{"KING-OF-SPAIN-CW", "King of Spain Contest (CW)"},
	{"KING-OF-SPAIN-SSB", "King of Spain Contest (SSB)"},
	{"LZ-DX", "LZ DX Contest"},
	{"MARCONI-MEMORIAL-CW", "Marconi Memorial CW Contest"},
	{"MEMORIAL-OK1WC", "Memorial OK1WC Contest"},
	{"NA-QSO-PARTY-CW", "North American QSO Party (CW)"},
	{"NA-QSO-PARTY-RTTY", "North American QSO Party (RTTY)"},
	{"NA-QSO-PARTY-SSB", "North American QSO Party (SSB)"},
	{"NCCC-SPRINT", "NCCC Sprint"},
	{"NORDIC-CW", "Nordic CW Contest"},
	{"OCEANIA-DX-CW", "Oceania DX Contest (CW)"},
	{"OCEANIA-DX-SSB", "Oceania DX Contest (SSB)"},
	{"OK-OM-DX-CW", "OK/OM DX Contest (CW)"},
	{"OK-OM-DX-SSB", "OK/OM DX Contest (SSB)"},
	{"PACC", "PACC Contest"},
	{"QCWA-QSO-PARTY", "QCWA QSO Party"},
	{"RADIO-TELEX-CW", "Radio Telex CW Contest"},
	{"RAEM", "RAEM Contest"},
	{"RDAC", "Russian District Award Contest"},
	{"RDXC", "Russian DX Contest"},
	{"RHEINLAND-PFALZ", "Rheinland-Pfalz Activity Days"},
	{"RSGB-IOTA", "RSGB IOTA Contest"},
	{"SARTG-WW-RTTY", "SARTG WW RTTY Contest"},
	{"SCC-RTTY", "SCC RTTY Championship"},
	{"SMP-CW", "SMP CW Contest"},
	{"SP-CONTEST-CW", "SP Contest (CW)"},
	{"SP-CONTEST-SSB", "SP Contest (SSB)"},
	{"SPRINT-PSK-63", "Sprint PSK 63"},
	{"TAC-LOGGER", "TAC Logger Contest"},
	{"TESLA-MEMORIAL-CW", "Tesla Memorial CW Contest"},
	{"TMC-RTTY", "TMC RTTY Contest"},
	{"TOEC-WW-GRID", "TOEC WW Grid Contest"},
	{"UBA-CW", "UBA CW Contest"},
	{"UBA-DX-CW", "UBA DX Contest (CW)"},
	{"UBA-DX-SSB", "UBA DX Contest (SSB)"},
	{"UBA-SSB", "UBA SSB Contest"},
	{"UKR-CHAMP-CW", "Ukrainian Championship (CW)"},
	{"UKR-CHAMP-SSB", "Ukrainian Championship (SSB)"},
	{"UK-DX-RTTY", "UK DX RTTY Contest"},
	{"URE-DX", "URE DX Contest"},
	{"US-COUNTIES-QSO-PARTY", "US Counties QSO Party"},
	{"VENEZ-IND-DAY", "Venezuelan Independence Day Contest"},
	{"WAG", "Worked All Germany Contest"},
	{"WEB-QSO-CW", "WEB QSO Party (CW)"},
	{"WEB-QSO-SSB", "WEB QSO Party (SSB)"},
	{"WIA-REMEMBRANCE-DAY", "WIA Remembrance Day Contest"},
	{"WW-DIGI-DX", "WW Digi DX Contest"},
	{"WW-EME", "WW EME Contest"},
	{"WW-SA", "WW South America Contest"},
	{"XUK-AC", "XUK Activity Contest"},
	{"YL-CONTEST-CW", "YL Contest (CW)"},
	{"YL-CONTEST-SSB", "YL Contest (SSB)"},
	{"YLRL-CONTEST", "YLRL Contest"},
	{"YODX-HF", "YO DX HF Contest"},

	// Field day / portable / special
	{"AADX-CW", "AADX CW Contest"},
	{"AADX-SSB", "AADX SSB Contest"},
	{"AGCW-DL-QRP", "AGCW DLP QRP Contest"},
	{"AGCW-DTC", "AGCW DTC Contest"},
	{"AGCW-HNY", "AGCW Happy New Year Contest"},
	{"AGCW-QRP-CONTEST", "AGCW QRP Contest"},
	{"AGCW-SPARTACUS", "AGCW Spartacus Contest"},
	{"AGCW-VHF-UHF", "AGCW VHF/UHF Contest"},
	{"ANARTS-RTTY", "ANARTS WW RTTY Contest"},
	{"ARI-DX", "ARI DX Contest"},
	{"BCC-QSO-PARTY", "BCC QSO Party"},
	{"BDXC", "British DX Club Contest"},
	{"BRAZILIAN-INDEPENDENCE", "Brazilian Independence Day Contest"},
	{"CARIBBEAN-OPEN", "Caribbean Open"},
	{"CDXC-SPRINT", "CDXC Sprint"},
	{"CIS-DX", "CIS DX Contest"},
	{"COUNTRY-FILE-CW", "Country File CW Contest"},
	{"CQC-WW-CW", "CQC WW CW Contest"},
	{"CQC-WW-SSB", "CQC WW SSB Contest"},
	{"CWT", "CWops Mini-CWT Test"},
	{"CWOPEN", "CW Open"},
	{"DARC-AFD", "DARC Activity Field Day"},
	{"DARC-FT4", "DARC FT4 Contest"},
	{"DIG-MODE-CONTEST-CW", "DIG Mode Contest CW"},
	{"DRCG-LONG-DX-RTTY", "DRCG Long DX RTTY Contest"},
	{"DRCG-WW-RTTY", "DRCG WW RTTY Contest"},
	{"EPC-CW", "EPC CW Contest"},
	{"EPC-RU-QSO-PARTY", "EPC Russia QSO Party"},
	{"EPC-WW-DX-CW", "EPC WW DX CW Contest"},
	{"EPC-WW-DX-SSB", "EPC WW DX SSB Contest"},
	{"ESA-HF", "ESA HF Championship"},
	{"EUCW-QSO-PARTY", "EUCW QSO Party"},
	{"FISTS", "FISTS CW Club Contest"},
	{"FT8DMC-ACTIVITY", "FT8DMC Activity Day"},
	{"HAL-QSO-PARTY", "HAL QSO Party"},
	{"HMC-CW", "HMC CW Contest"},
	{"HOLYLAND-CW", "Holyland CW Contest"},
	{"HOLYLAND-DX", "Holyland DX Contest"},
	{"HOLYLAND-SSB", "Holyland SSB Contest"},
	{"ICWC-MST", "ICWC Medium Speed Test"},
	{"IL-VHF", "IL VHF Contest"},
	{"INDEPENDENCE-DAY-RI", "Independence Day RI Contest"},
	{"IOTA-CONTEST", "IOTA Contest"},
	{"JARTS-WW-RTTY", "JARTS WW RTTY Contest"},
	{"JASTA-CW", "JASTA CW Contest"},
	{"K1USN-SST", "K1USN Slow Speed Test"},
	{"KAR-WW-DX-CW", "KAR WW DX CW Contest"},
	{"KAR-WW-DX-SSB", "KAR WW DX SSB Contest"},
	{"KM0T-QSO-PARTY", "KM0T QSO Party"},
	{"LDC-QSO-PARTY", "LDC QSO Party"},
	{"LZ-OPEN-CW", "LZ Open CW Contest"},
	{"LZ-OPEN-SSB", "LZ Open SSB Contest"},
	{"MARCONI-MEMORIAL-CW", "Marconi Memorial CW Contest"},
	{"MINITEST-CW", "Minitest CW"},
	{"MINITEST-SSB", "Minitest SSB"},
	{"NA-VHF-SPRINT", "NA VHF Sprint"},
	{"NAQCC-EU-SPRINT", "NAQCC-EU Monthly Sprint"},
	{"NAQCC-MW-SPRINT", "NAQCC MW Sprint"},
	{"NCCC-SPRINT", "NCCC Sprint"},
	{"NDXC-CW", "NDXC CW Contest"},
	{"NEQP", "New England QSO Party"},
	{"NJ-QSO-PARTY", "New Jersey QSO Party"},
	{"NRAU-BALTIC-CW", "NRAU Baltic Contest (CW)"},
	{"NRAU-BALTIC-SSB", "NRAU Baltic Contest (SSB)"},
	{"ON-CONTEST", "ON Contest"},
	{"OPEN-Ukraine-RTTY", "Open Ukraine RTTY Championship"},
	{"PA-QSO-PARTY", "Pennsylvania QSO Party"},
	{"PACC", "PACC Contest"},
	{"PACC-RTTY", "PACC RTTY Contest"},
	{"PODXS-070-CLUB", "PODXS 070 Club PSK31 Contest"},
	{"RAC-CANADA-DAY", "RAC Canada Day Contest"},
	{"RAC-CANADA-WINTER", "RAC Canada Winter Contest"},
	{"RAEM", "RAEM Contest"},
	{"RDAC", "Russian District Award Contest"},
	{"RDXC", "Russian DX Contest"},
	{"REF-RA", "REF RA Contest"},
	{"RSGB-1.8-MHZ", "RSGB 1.8 MHz Contest"},
	{"RSGB-AFS", "RSGB AFS Contest"},
	{"RSGB-CLUB-CALLS", "RSGB Club Calls Contest"},
	{"RSGB-COMMONWEALTH", "RSGB Commonwealth Contest"},
	{"RSGB-IOTA", "RSGB IOTA Contest"},
	{"RSGB-LOW-POWER", "RSGB Low Power Field Day"},
	{"RSGB-NFD", "RSGB National Field Day"},
	{"RSGB-ROPOCO", "RSGB RoPoCo"},
	{"RUN-FOR-THE-BACON", "Run for the Bacon QRP Contest"},
	{"SAC-CW", "Scandinavian Activity Contest (CW)"},
	{"SAC-SSB", "Scandinavian Activity Contest (SSB)"},
	{"SMP-CW", "SMP CW Contest"},
	{"SP-DX-CONTEST", "SP DX Contest"},
	{"SP-CONTEST-CW", "SP Contest (CW)"},
	{"SP-CONTEST-SSB", "SP Contest (SSB)"},
	{"SPDXCONTEST-CW", "SP DX Contest (CW)"},
	{"SPDXCONTEST-RTTY", "SP DX Contest (RTTY)"},
	{"SPDXCONTEST-SSB", "SP DX Contest (SSB)"},
	{"SSC-SPRINT", "SSC Sprint"},
	{"STEW-PERRY", "Stew Perry Topband Challenge"},
	{"TARA-DIP-40", "TARA Dipole 40m Contest"},
	{"TARA-GRID-DIP", "TARA Grid Dip Contest"},
	{"TARA-PSK-RUMBLE", "TARA PSK Rumble Contest"},
	{"TARA-RTTY-MELEE", "TARA RTTY Melee"},
	{"TARA-SKIRMISH", "TARA Skirmish Contest"},
	{"TESLA-MEMORIAL-CW", "Tesla Memorial CW Contest"},
	{"TMC-RTTY", "TMC RTTY Contest"},
	{"TOEC-WW-GRID", "TOEC WW Grid Contest"},
	{"TX-QSO-PARTY", "Texas QSO Party"},
	{"UBA-CW", "UBA CW Contest"},
	{"UBA-DX-CW", "UBA DX Contest (CW)"},
	{"UBA-DX-SSB", "UBA DX Contest (SSB)"},
	{"UBA-PSK63", "UBA PSK63 Contest"},
	{"UBA-SSB", "UBA SSB Contest"},
	{"UKEICC-80M", "UKEICC 80m Contest"},
	{"UKEICC-DX-CW", "UKEICC DX Contest (CW)"},
	{"UKEICC-DX-SSB", "UKEICC DX Contest (SSB)"},
	{"UKR-CHAMP-CW", "Ukrainian Championship (CW)"},
	{"UKR-CHAMP-SSB", "Ukrainian Championship (SSB)"},
	{"UKR-DX-CW", "Ukrainian DX Contest (CW)"},
	{"UKR-DX-SSB", "Ukrainian DX Contest (SSB)"},
	{"URE-DX", "URE DX Contest"},
	{"US-COUNTIES-QSO-PARTY", "US Counties QSO Party"},
	{"VHF-UHF-FT8", "VHF UHF FT8 Contest"},
	{"WAG", "Worked All Germany Contest"},
	{"WEB-QSO-CW", "WEB QSO Party (CW)"},
	{"WEB-QSO-SSB", "WEB QSO Party (SSB)"},
	{"WIA-REMEMBRANCE-DAY", "WIA Remembrance Day Contest"},
	{"WINTER-FD", "Winter Field Day"},
	{"WRTCCW", "Worldwide Radio Telegraphy Contest (CW)"},
	{"WRTCRTTY", "Worldwide Radio Telegraphy Contest (RTTY)"},
	{"WRTSSSB", "Worldwide Radio Telegraphy Contest (SSB)"},
	{"WW-DIGI-DX", "WW Digi DX Contest"},
	{"WW-SA", "WW South America Contest"},
	{"XMAS-RTTY", "XMAS RTTY Contest"},
	{"YB-DX-CW", "YB DX Contest (CW)"},
	{"YB-DX-SSB", "YB DX Contest (SSB)"},
	{"YB-DX-RTTY", "YB DX Contest (RTTY)"},
	{"YL-CONTEST-CW", "YL Contest (CW)"},
	{"YL-CONTEST-SSB", "YL Contest (SSB)"},
	{"YO-HF", "YO HF Contest"},
	{"YODX-HF", "YO DX HF Contest"},
	{"YUDX-CONTEST", "YU DX Contest"},
	{"Z60A-NEW-YEAR", "Z60A New Year Contest"},
}

// adifContestIDList builds an ordered, deduplicated list of Contest-ID values for Space cycling.
func adifContestIDList() []string {
	seen := make(map[string]bool, len(adifContestIDs))
	list := make([]string, 0, len(adifContestIDs))
	for _, e := range adifContestIDs {
		if !seen[e.ID] {
			seen[e.ID] = true
			list = append(list, e.ID)
		}
	}
	return list
}

// isValidContestID reports whether s matches an ADIF Contest-ID exactly (case-sensitive).
func isValidContestID(s string) bool {
	for _, e := range adifContestIDs {
		if e.ID == s {
			return true
		}
	}
	return false
}

// contestIDDesc returns the ADIF description for a Contest-ID, or "" if not found.
func contestIDDesc(s string) string {
	for _, e := range adifContestIDs {
		if e.ID == s {
			return e.Desc
		}
	}
	return ""
}

// nextContestID returns the Contest-ID that follows prev in the sorted list.
// When prev is empty or not found it returns the first entry.
func nextContestID(prev string) string {
	list := adifContestIDList()
	if prev == "" {
		return list[0]
	}
	for i, id := range list {
		if id == prev {
			return list[(i+1)%len(list)]
		}
	}
	return list[0]
}
