package config

func DefaultConfig() *Config {
	tz := SystemTimezone()
	defaultRigID := NewID("default-rig")
	defaultLogbookID := NewID("default-logbook")

	return &Config{
		General: GeneralConfig{
			Timezone:         tz,
			Units:            "metric",
			PictureAtQRZPane: false,
			SolarAtQSOPane:   true,
			UseCTY:           true,
			UseSCP:           true,
			UseRef:           true,
			Debug:            false,
			Notifications: NotificationsConfig{
				Enabled:       true,
				QSO:           false,
				Wavelog:       false,
				WavelogErrors: true,
			},
		},
		State: StateConfig{
			ActiveLogbook: defaultLogbookID,
		},
		Logbooks: map[string]Logbook{
			defaultLogbookID: {
				ID:      defaultLogbookID,
				Name:    "Default",
				Station: Station{},
				ADIF:    ADIFConfig{},
			},
		},
		Rigs: map[string]RigPreset{
			defaultRigID: {
				ID: defaultRigID,
			},
		},
	}
}

func DefaultBroadcastStations() []BroadcastStation {
	return []BroadcastStation{
		{Radio: "Radio Antena Satelor", Country: "Romania", FrequencyKHz: 153},
		{Radio: "Mongolian National Radio 1", Country: "Mongolia", FrequencyKHz: 164},
		{Radio: "M\u00e9di 1", Country: "Morocco", FrequencyKHz: 171},
		{Radio: "BBC Radio 4 LW", Country: "United Kingdom", FrequencyKHz: 198},
		{Radio: "Mongolian National Radio 1", Country: "Mongolia", FrequencyKHz: 209},
		{Radio: "Polskie Radio Jedynka", Country: "Poland", FrequencyKHz: 225},
		{Radio: "Mongolian National Radio 1", Country: "Mongolia", FrequencyKHz: 227},
		{Radio: "Radio Alg\u00e9rie Cha\u00eene 3", Country: "Algeria", FrequencyKHz: 252},
		{Radio: "Radio Antena Satelor", Country: "Romania", FrequencyKHz: 531},
		{Radio: "Kossuth R\u00e1di\u00f3", Country: "Hungary", FrequencyKHz: 540},
		{Radio: "Radio Rom\u00e2nia Actualit\u0103\u0163i", Country: "Romania", FrequencyKHz: 558},
		{Radio: "BNR Horizont", Country: "Bulgaria", FrequencyKHz: 576},
		{Radio: "CyBC Radio 3", Country: "Cyprus", FrequencyKHz: 603},
		{Radio: "Radio Rom\u00e2nia Actualit\u0103\u0163i", Country: "Romania", FrequencyKHz: 612},
		{Radio: "Radio Caroline", Country: "United Kingdom", FrequencyKHz: 648},
		{Radio: "BBC Radio 5 Live", Country: "United Kingdom", FrequencyKHz: 693},
		{Radio: "BBC Radio Scotland", Country: "United Kingdom", FrequencyKHz: 810},
		{Radio: "Radio Rom\u00e2nia Actualit\u0103\u0163i", Country: "Romania", FrequencyKHz: 855},
		{Radio: "WSM", Country: "United States", FrequencyKHz: 650},
		{Radio: "WLW", Country: "United States", FrequencyKHz: 700},
		{Radio: "WOR", Country: "United States", FrequencyKHz: 710},
		{Radio: "CFZM", Country: "Canada", FrequencyKHz: 740},
		{Radio: "WSB", Country: "United States", FrequencyKHz: 750},
		{Radio: "WABC", Country: "United States", FrequencyKHz: 770},
		{Radio: "WCBS", Country: "United States", FrequencyKHz: 880},
		{Radio: "WINS", Country: "United States", FrequencyKHz: 1010},
		{Radio: "WBZ", Country: "United States", FrequencyKHz: 1030},
		{Radio: "KFAQ", Country: "United States", FrequencyKHz: 1170},
		{Radio: "Domestic Shortwave Australia", Country: "Australia", FrequencyKHz: 2310},
		{Radio: "Domestic Shortwave Australia", Country: "Australia", FrequencyKHz: 2325},
		{Radio: "Domestic Shortwave Australia", Country: "Australia", FrequencyKHz: 2485},
		{Radio: "BBC World Service", Country: "United Kingdom", FrequencyKHz: 3255},
		{Radio: "Voice of Indonesia", Country: "Indonesia", FrequencyKHz: 3325},
		{Radio: "Radio Sonder Grense", Country: "South Africa", FrequencyKHz: 3325},
		{Radio: "Radio Exterior de Espa\u00f1a", Country: "Spain", FrequencyKHz: 3340},
		{Radio: "Shortwave Gold", Country: "Germany", FrequencyKHz: 3950},
		{Radio: "KBS World Radio", Country: "South Korea", FrequencyKHz: 3955},
		{Radio: "Radio France Internationale", Country: "France", FrequencyKHz: 3965},
		{Radio: "Shortwave Gold", Country: "Germany", FrequencyKHz: 3975},
		{Radio: "HCJB Deutschland", Country: "Germany", FrequencyKHz: 3995},
		{Radio: "China National Radio 1", Country: "China", FrequencyKHz: 4750},
		{Radio: "Radio Tarma", Country: "Peru", FrequencyKHz: 4775},
		{Radio: "Xizang PBS", Country: "China", FrequencyKHz: 4820},
		{Radio: "WWCR", Country: "United States", FrequencyKHz: 4840},
		{Radio: "Voice of America", Country: "United States", FrequencyKHz: 4930},
		{Radio: "R\u00e1dio Brasil Central", Country: "Brazil", FrequencyKHz: 4985},
		{Radio: "Radio Rebelde", Country: "Cuba", FrequencyKHz: 5025},
		{Radio: "Beibu Bay Radio", Country: "China", FrequencyKHz: 5050},
		{Radio: "Radio Taiwan International", Country: "Taiwan", FrequencyKHz: 5900},
		{Radio: "Voice of Turkey", Country: "T\u00fcrkiye", FrequencyKHz: 5960},
		{Radio: "China Radio International", Country: "China", FrequencyKHz: 5965},
		{Radio: "Radio Romania International", Country: "Romania", FrequencyKHz: 6040},
		{Radio: "CFRX Toronto", Country: "Canada", FrequencyKHz: 6070},
		{Radio: "Voice of America", Country: "United States", FrequencyKHz: 6080},
		{Radio: "Voice of Korea", Country: "North Korea", FrequencyKHz: 6170},
		{Radio: "BBC World Service", Country: "United Kingdom", FrequencyKHz: 6195},
		{Radio: "Voice of Nigeria", Country: "Nigeria", FrequencyKHz: 7255},
		{Radio: "China Radio International", Country: "China", FrequencyKHz: 7285},
		{Radio: "China Radio International", Country: "China", FrequencyKHz: 7325},
		{Radio: "Vatican Radio", Country: "Vatican City", FrequencyKHz: 7360},
		{Radio: "Radio Romania International", Country: "Romania", FrequencyKHz: 7420},
		{Radio: "WRMI", Country: "United States", FrequencyKHz: 7455},
		{Radio: "KTWR Trans World Radio", Country: "Guam", FrequencyKHz: 7500},
		{Radio: "BBC World Service", Country: "United Kingdom", FrequencyKHz: 9410},
		{Radio: "Voice of Korea", Country: "North Korea", FrequencyKHz: 9435},
		{Radio: "Radio Taiwan International", Country: "Taiwan", FrequencyKHz: 9545},
		{Radio: "KBS World Radio", Country: "South Korea", FrequencyKHz: 9570},
		{Radio: "Radio Exterior de Espa\u00f1a", Country: "Spain", FrequencyKHz: 9690},
		{Radio: "Radio Romania International", Country: "Romania", FrequencyKHz: 9700},
		{Radio: "Radio New Zealand Pacific", Country: "New Zealand", FrequencyKHz: 9700},
		{Radio: "Vatican Radio", Country: "Vatican City", FrequencyKHz: 9705},
		{Radio: "Radio Habana Cuba", Country: "Cuba", FrequencyKHz: 9710},
		{Radio: "Voice of Turkey", Country: "T\u00fcrkiye", FrequencyKHz: 9875},
		{Radio: "China Radio International", Country: "China", FrequencyKHz: 11650},
		{Radio: "Radio New Zealand Pacific", Country: "New Zealand", FrequencyKHz: 11725},
		{Radio: "KBS World Radio", Country: "South Korea", FrequencyKHz: 11810},
		{Radio: "AWR", Country: "International", FrequencyKHz: 11880},
		{Radio: "Radio Romania International", Country: "Romania", FrequencyKHz: 11925},
		{Radio: "Radio Exterior de Espa\u00f1a", Country: "Spain", FrequencyKHz: 12030},
		{Radio: "BBC World Service", Country: "United Kingdom", FrequencyKHz: 12095},
		{Radio: "Voice of Korea", Country: "North Korea", FrequencyKHz: 12120},
		{Radio: "Radio Free Asia", Country: "United States", FrequencyKHz: 13580},
		{Radio: "BBC World Service", Country: "United Kingdom", FrequencyKHz: 13610},
		{Radio: "China Radio International", Country: "China", FrequencyKHz: 13635},
		{Radio: "Voice of Turkey", Country: "T\u00fcrkiye", FrequencyKHz: 13670},
		{Radio: "China Radio International", Country: "China", FrequencyKHz: 13760},
		{Radio: "Voice of Korea", Country: "North Korea", FrequencyKHz: 13760},
		{Radio: "Ifrikya FM", Country: "Algeria", FrequencyKHz: 13790},
		{Radio: "BBC World Service", Country: "United Kingdom", FrequencyKHz: 13790},
		{Radio: "China Radio International", Country: "China", FrequencyKHz: 15110},
		{Radio: "BBC World Service", Country: "United Kingdom", FrequencyKHz: 15135},
		{Radio: "Radio Romania International", Country: "Romania", FrequencyKHz: 15240},
		{Radio: "Voice of America", Country: "United States", FrequencyKHz: 15280},
		{Radio: "Radio Kuwait", Country: "Kuwait", FrequencyKHz: 15530},
		{Radio: "Voice of America", Country: "United States", FrequencyKHz: 15580},
		{Radio: "Radio Exterior de Espa\u00f1a", Country: "Spain", FrequencyKHz: 15680},
		{Radio: "WRMI", Country: "United States", FrequencyKHz: 15770},
		{Radio: "Radio Romania International", Country: "Romania", FrequencyKHz: 17530},
		{Radio: "Voice of America", Country: "United States", FrequencyKHz: 17565},
		{Radio: "BBC World Service", Country: "United Kingdom", FrequencyKHz: 17590},
		{Radio: "China Radio International", Country: "China", FrequencyKHz: 17675},
		{Radio: "Radio New Zealand Pacific", Country: "New Zealand", FrequencyKHz: 17740},
		{Radio: "Radio Exterior de Espa\u00f1a", Country: "Spain", FrequencyKHz: 17755},
		{Radio: "China Radio International", Country: "China", FrequencyKHz: 17790},
		{Radio: "BBC World Service", Country: "United Kingdom", FrequencyKHz: 18910},
		{Radio: "Radio Free Asia", Country: "United States", FrequencyKHz: 18930},
		{Radio: "China Radio International", Country: "China", FrequencyKHz: 18970},
		{Radio: "BBC World Service", Country: "United Kingdom", FrequencyKHz: 21525},
		{Radio: "Radio Free Asia", Country: "United States", FrequencyKHz: 21555},
		{Radio: "Radio Exterior de Espa\u00f1a", Country: "Spain", FrequencyKHz: 21670},
		{Radio: "China Radio International", Country: "China", FrequencyKHz: 21695},
		{Radio: "Radio Saudi", Country: "Saudi Arabia", FrequencyKHz: 21735},
		{Radio: "Radio France Internationale", Country: "France", FrequencyKHz: 21780},
		{Radio: "Radio France Internationale", Country: "France", FrequencyKHz: 25710},
		{Radio: "World Music Radio", Country: "Denmark", FrequencyKHz: 25800},
		{Radio: "BBC World Service", Country: "United Kingdom", FrequencyKHz: 25900},
	}
}
